export const CREATE_TODO_LIST = 'CREATE_TODO_LIST';
export const REMOVE_TODO_LIST = 'REMOVE_TODO_LIST';

export const ADD_TODO_LIST_ITEM = 'ADD_TODO_LIST_ITEM';
export const REMOVE_TODO_LIST_ITEM = 'REMOVE_TODO_LIST_ITEM';
export const EDIT_TODO_LIST_ITEM = 'EDIT_TODO_LIST_ITEM';
export const TOGGLE_COMPLETE_TODO_LIST_ITEM = 'TOGGLE_COMPLETE_TODO_LIST_ITEM';
